### ISSUE TITLE
add objects July

### ISSUE THREAD

**Issue by oliviervd** [oliviervd/dmg-programstudios#221]
@thijstem kan jij de objecten toevoegen die in juli gepubliceerd werden; 

wat je moet doen; hier lijn toevoegen met array van de objectnummers. 
https://github.com/oliviervd/dmg-programstudios/blob/8000f9ffa4572034db9b8f6ed5485003a8b5d57a/src/components/elements/indexes/newItems.jsx#L19 

hier <p> tag --> https://github.com/oliviervd/dmg-programstudios/blob/8000f9ffa4572034db9b8f6ed5485003a8b5d57a/src/components/elements/indexes/newItems.jsx#L106 

best pull request maken als dat kan.  --> je kan gewoon editen in Github, dus in principe hoef je het niet te clonen. maar kan uiteraard ook. 

https://github.com/oliviervd/dmg-programstudios/tree/221-add-objects-july

**Comment by oliviervd** [comment]
mag deze al afgesloten worden of wachten tot wanneer de objecten binnenkomen?

**Comment by thijstem** [comment]
Zou hiermee nog wachten, sync van de R-schijf is nog niet gebeurd dus import ook niet.
